baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

title ="NOVA CTF"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  homeSubtitle = "FCT @ NOVA"

  # Metadata mostly used in document's head
  description = "Homepage and blog by NOVA CTF"
  keywords = "homepage, blog, science, informatics, development, programming, security"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"
  # Colors for favicons
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"
  [params.logo]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#04d334"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"



[languages]
  [languages.en]
    subtitle = "FCT @ UNL"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

# Social icons
[[params.social]]
  name = "email"
  url  = "mailto:cibersegurancafct@gmail.com"

[[params.social]]
  name = "github"
  url  = "https://github.com/novactf"

# Menu
[menu]
[[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  # [[menu.main]]
  #   identifier = "blog"
  #   name       = "Blog"
  #   url        = "/posts"
  # [[menu.main]]
  #   identifier = "challenges"
  #   name       = "Challenges"
  #   url        = "/challenges"
  [[menu.main]]
    identifier = "discord"
    name       = "Sign Up"
    url        ="https://discord.gg/BqUuGsY"
